version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: doce-hub-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: docehub123!@#
      MYSQL_DATABASE: doce_hub_db
      MYSQL_USER: docehub
      MYSQL_PASSWORD: docehub123!@#
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: